
[features]
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]

[package]
name = "skinsol"
version = "0.1.0"
edition = "2021"

[lib]
name = "skinsol"
crate-type = ["cdylib", "lib"]

[dependencies]
anchor-lang = "0.31.1"
anchor-spl = "0.31.1"

